### ISSUE TITLE
Crash after 2s loading in brand new world [1.18.2 Fabric]

### ISSUE THREAD

**Issue by valkyrienyanko** [WolfieWaffle/Hardcore-Torches-Fabric#7]
![image](https://user-images.githubusercontent.com/6277739/178116607-7b6a13e0-2e8e-4b73-8c37-a047762eaedb.png)

## Steps to Reproduce
1. Install the following modpack through curseforge [The Energy Race v5.zip](https://github.com/WolfieWaffle/Hardcore-Torches-Fabric/files/9077597/The.Energy.Race.v5.zip) (import as previously created modpack)
2. Create new world
3. Wait 1 - 2 seconds
4. Notice crash

## Crash Log
NotEnoughCrashes: https://crashy.net/8rBRXz1xEafCht78M7W7

```
---- Minecraft Crash Report ----
// There are four lights!

Time: 7/9/22, 12:26 PM
Description: Exception in server tick loop

java.lang.ExceptionInInitializerError
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3)
	at com.github.wolfiewaffle.hardcore_torches.loot.FatLootNumberProvider.getType(FatLootNumberProvider.java:35)
	at net.minecraft.util.JsonSerializing$GsonSerializer.serialize(JsonSerializing:114)
	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81)
	at com.google.gson.Gson.toJson(Gson.java:735)
	at com.google.gson.Gson.toJsonTree(Gson.java:628)
	at com.google.gson.Gson.toJsonTree(Gson.java:607)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.serialize(TreeTypeAdapter.java:155)
	at net.minecraft.loot.LootPool$Serializer.serialize(LootPool:184)
	at net.minecraft.loot.LootPool$Serializer.serialize(LootPool:169)
	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
	at com.google.gson.internal.bind.ArrayTypeAdapter.write(ArrayTypeAdapter.java:95)
	at com.google.gson.Gson.toJson(Gson.java:735)
	at com.google.gson.Gson.toJsonTree(Gson.java:628)
	at com.google.gson.Gson.toJsonTree(Gson.java:607)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.serialize(TreeTypeAdapter.java:155)
	at net.minecraft.loot.LootTable$Serializer.serialize(LootTable:239)
	at net.minecraft.loot.LootTable$Serializer.serialize(LootTable:209)
	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81)
	at com.google.gson.Gson.toJson(Gson.java:735)
	at com.google.gson.Gson.toJsonTree(Gson.java:628)
	at com.google.gson.Gson.toJsonTree(Gson.java:607)
	at uk.me.desert_island.rer.RoughlyEnoughResources.sendLootToPlayers(RoughlyEnoughResources.java:53)
	at net.minecraft.server.PlayerManager.handler$ekn002$onPlayerConnect(PlayerManager:7957)
	at net.minecraft.server.PlayerManager.onPlayerConnect(PlayerManager:282)
	at net.minecraft.server.network.ServerLoginNetworkHandler.addToServer(ServerLoginNetworkHandler:130)
	at net.minecraft.server.network.ServerLoginNetworkHandler.acceptPlayer(ServerLoginNetworkHandler:117)
	at net.minecraft.server.network.ServerLoginNetworkHandler.redirect$chf000$handlePlayerJoin(ServerLoginNetworkHandler:563)
	at net.minecraft.server.network.ServerLoginNetworkHandler.tick(ServerLoginNetworkHandler:67)
	at net.minecraft.network.ClientConnection.tick(ClientConnection:243)
	at net.minecraft.server.ServerNetworkIo.tick(ServerNetworkIo:183)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:918)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:851)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer:97)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:273)
	at java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalStateException: Registry is already frozen (trying to add key ResourceKey[minecraft:loot_number_provider_type / hardcore_torches:fat])
	at net.minecraft.util.registry.SimpleRegistry.assertNotFrozen(SimpleRegistry:80)
	at net.minecraft.util.registry.SimpleRegistry.set(SimpleRegistry:90)
	at net.minecraft.util.registry.SimpleRegistry.set(SimpleRegistry:86)
	at net.minecraft.util.registry.SimpleRegistry.add(SimpleRegistry:134)
	at net.minecraft.util.registry.Registry.register(Registry:471)
	at net.minecraft.util.registry.Registry.register(Registry:467)
	at com.github.wolfiewaffle.hardcore_torches.loot.HCTLootNumberProviderTypes.register(HCTLootNumberProviderTypes.java:13)
	at com.github.wolfiewaffle.hardcore_torches.loot.HCTLootNumberProviderTypes.<clinit>(HCTLootNumberProviderTypes.java:10)
	... 37 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2925562368 bytes (2790 MiB) / 7046430720 bytes (6720 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 5
	Microarchitecture: unknown
	Frequency (GHz): 2.90
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Radeon RX 580 Series
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x67df
	Graphics card #0 versionInfo: DriverVersion=30.0.15021.11005
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 21178.51
	Virtual memory used (MB): 18642.88
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 77.68
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -Xms256m
	Fabric Mods: 
		additionaladditions: Additional Additions 4.0.5
		advancementplaques: Advancement Plaques 1.4.5
		advdebug: Advancements Debug 2.3.0
		ae2: Applied Energistics 2 11.1.4
			noindium: No Indium? 1.0.2+1.18.2
		ae2wtlib: AE2WTLib 11.1.3
		ambientenvironment: Ambient Environment 7.0+19
		ambientsounds: Ambiend Sounds (Fabric) 5.0.16
		antighost: AntiGhost 1.18.2-fabric0.47.10-1.1.4
			crowdin-translate: CrowdinTranslate 1.4+1.18.2
		appleskin: AppleSkin 2.4.0+mc1.18.2
		aqupdgrizzly: Grizzly Bear mob 1.18-1.3
		architectury: Architectury 4.5.76
		attributefix: AttributeFix 14.0.2
		automated_crafting: Automated Crafting 1.4.4
		auudio: Auudio 1.0.3
		badwithernocookiereloaded: Bad Wither No Cookie! Reloaded 3.10.18 (Fabric 1.18.2)
		balm-fabric: Balm 3.1.0+0
		bcc: BetterCompatibilityChecker fabric-1.0.5
		bclib: BCLib 1.4.7
		beo: Basic End Ores 1.18.2-2.1.0-Fabric
		betteradvancements: Better Advancements 0.2.1.132
		betteranimalsplus: Better Animals Plus 1.18.2-11.0.5
		betterdeserttemples: YUNG's Better Desert Temples 1.18.2-Fabric-1.2
		betterdungeons: YUNG's Better Dungeons 1.18.2-Fabric-2.1.0
		betterfpsdist: Better FPS distance Mod 1.18-1.8
		bettermineshafts: YUNG's Better Mineshafts 1.18.2-Fabric-2.2
		betterpingdisplay: Better Ping Display 1.1.1
		betterstrongholds: YUNG's Better Strongholds 1.18.2-Fabric-2.1.1
		betterthirdperson: Better Third Person 1.8.1
		betterwitchhuts: YUNG's Better Witch Huts 1.18.2-Fabric-1.0.1
		blur: Blur (Fabric) 2.4.1
			midnightlib: MidnightLib 0.3.1
			satin: Satin 1.7.0
		bno: Basic Nether Ores 1.18.2-7.2.0-Fabric
		boatcontainer: BoatContainer 1.2.1
		bookshelf: Bookshelf 13.2.21
		bowinfinityfix: Bow Infinity Fix rv11
		carrier: Carrier 1.10.0
			advanced_runtime_resource_pack: Runtime Resource Pack 0.5.5
		charm: Charm 4.1.2
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		chat_heads: Chat Heads 0.6.0
		chunky: Chunky 1.2.164
		cleancut: CleanCut 1.18.2-5.0-fabric
		clickadv: Clickable Advancements Mod 2.6
		climbladdersfast: ClimbLaddersFast 2.2.2-1.18
		cloth-api: Cloth API 3.2.64
			cloth-client-events-v0: Cloth Client Events v0 3.2.64
			cloth-common-events-v1: Cloth Common Events v1 3.2.64
			cloth-datagen-api-v1: Cloth Datagen v1 3.2.64
			cloth-scissors-api-v1: Cloth Scissors API v1 3.2.64
			cloth-utils-v1: Cloth Utils v1 3.2.64
		cloth-config: Cloth Config v6 6.2.62
			cloth-basic-math: cloth-basic-math 0.6.1
		connectivity: Connectivity Mod 1.18.2-3.3
		controlling: Controlling For Fabric 9.0+21
		crafttweaker: CraftTweaker 9.1.162
			org_javassist_javassist: javassist 3.29.0-GA
			org_reflections_reflections: reflections 0.10.2
		create: Create mc1.18.2_v0.4.1+637
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			fake-player-api: Fake Player API 0.3.0
			flywheel: Flywheel 1.18-0.7.0.26
			forge_tags: Forge Tags 2.1
			milk: Milk Lib 0.3.2
				dripstone_fluid_lib: Dripstone Fluid Lib 1.2.0
			porting_lib: Porting Lib 1.1.317-beta+1.18.2-dev.7ad1f24
				com_github_llamalad7_mixinextras: MixinExtras 0.0.10
				serialization_hooks: Serialization Hooks 0.2.0+1.18.f5d4aa6
			reach-entity-attributes: Reach Entity Attributes 2.1.1
			registrate-fabric: Registrate for Fabric MC1.18.2-1.0.3
		createaddition: Create Crafts & Additions ${version}
			team_reborn_energy: Energy 2.2.0
		createchunkloading: Create Chunkloading 1.1.0
		createplus: CreatePlus 1.0
		creativecore: CreativeCore (Fabric) 2.6.12
		creeperoverhaul: Creeper Overhaul 1.3.1
		croptopia: Croptopia 2.0.5
			com_typesafe_config: config 1.4.1
			io_leangen_geantyref_geantyref: geantyref 1.3.11
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		cullleaves: Cull Leaves 2.3.2
		cyti: Can You Trash It? 1.0.5
		dadobugbedrockores: Dadobug1111's Bedrock Ores 1.3.6
		damagetilt: Damage Tilt 1.18-fabric-0.1.2
		darkness: True Darkness 2.0.91
		dawn: Dawn API 3.3.2
		denseores: Dense Ores: Refabricated 1.2.2+1.18.2
			omega-config: OmegaConfig 1.2.3-1.18.1
			omega-config-gui: Omega Config GUI 1.2.3-1.18.1
				cloth-config-lite: cloth-config-lite 2.0.6
		disable_custom_worlds_advice: Disable Custom Worlds Advice 2.0
		dragonloot: DragonLoot 1.1.0
		drippyloadingscreen: Drippy Loading Screen 1.6.4
		dual_riders: Dual Riders 1.1.1
		dynview: Dynamic View Mod 1.18.2-2.2
		effective: Effective 1.2.1
		enchdesc: EnchantmentDescriptions 10.0.4
		enderore: Ender Ore 1.18.2-1.2.3
		enhancedvisuals: Enhanced Visuals (Fabric) 1.5.5
		entityculling: EntityCulling-Fabric 1.5.1
		experiencebugfix: Experience Bug Fix 18
		extraalchemy: Extra Alchemy 1.8.1
		extractinatortweaks: Extractinator Tweaks 1.0-SNAPSHOT-3
		fabric: Fabric API 0.57.0+1.18.2
			fabric-api-base: Fabric API Base 0.4.4+d7c144a860
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.2+2373a54560
			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.6+651bcc5960
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
			fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
			fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
			fabric-containers-v0: Fabric Containers (v0) 0.1.22+d7c144a860
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.1.1+c85f2e3860
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 3.0.0+9fcb91d260
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.20+489d6f8260
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.18+d7c144a860
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
			fabric-item-api-v1: Fabric Item API (v1) 1.5.1+6c4e5d0960
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.14+91896a4960
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+cc71601c60
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.0+1997ad1260
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.2+e747827960
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.4+cc71601c60
			fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.22+e6b169eb60
			fabric-networking-v0: Fabric Networking (v0) 0.3.9+b4f4f6cd60
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.3+032c981d60
			fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.9+0d9ab37260
			fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.5.2+d005b03a60
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.2+446e059560
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.1+1f6558e860
			fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.3+f4563ac860
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.0+e747827960
		fabric-language-kotlin: Fabric Language Kotlin 1.8.1+kotlin.1.7.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.3
		fabric-language-scala: Fabric Language Scala 1.1.0+scala.2.13.6
		fabricloader: Fabric Loader 0.14.8
		fabricshieldlib: Fabric Shield Lib 1.5.3-1.18
			mm: Manningham Mills 2.3
		fallingleaves: Falling Leaves 1.11.1+1.18.2
		fallingtree: FallingTree 3.5.3
		farsight: Farsight Mod 1.18-1.9
		fatxporbs: Fat Experience Orbs 2.0.1
		faux-custom-entity-data: Faux-Custom-Entity-Data 1.0.4
		feature_nbt_deadlock_be_gone: Feature NBT Deadlock Be Gone - Fabric 2.0.0+1.18.2-rc1
		ferritecore: FerriteCore 4.2.1
		flesh2leather: Flesh2Leather 1.0.3+1.18.2
		flytre_lib: FlytreLib 1.8.1
		forgeconfigapiport: Forge Config API Port 3.2.0
		fpsreducer: FPS Reducer 1.18.2-2.0
		ftblibrary: FTB Library 1802.3.6-build.123
		ftbultimine: FTB Ultimine 1802.3.3-build.55
		gearreborn: Gear Reborn 1.18.2-0.1.14
			autoconfig1u: Auto Config v1 Updated 3.4.0
		geckolib3: Geckolib 3.0.50
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		go-fish: Go Fish 1.5.0-1.18.2
		graveyard: The Graveyard 1.9
		graveyard_biomes: The Graveyard Biomes 1.1
		guardvillagers: Guard Villagers Fabric 1.18.2-1.0.14
		hardcore_torches: Hardcore Torches 1.18.2-1.6
		iceberg: Iceberg 1.0.38
		iknowwhatimdoing: I Know What I'm Doing 4.1.0
		ikwid_fabric: I know what I'm doing! [FABRIC] 1.1+1.18.x
		immersive_weathering: Immersive Weathering 2.5.6
		impactfulweather: Biome Particle Weather 2.4.8
		improved-stations: Improved Stations 2.1.0
		indium: Indium 1.0.6+mc1.18.2
		infusion_table: Infusion Table 1.1.0
		ingredient-extension-api: Ingredient Extension API 2.0.6
		initialinventory: Initial Inventory 6.0.8
		iris: Iris 1.2.5
			org_anarres_jcpp: jcpp 1.4.14
		ironchests: Iron Chests 1.7.2
			libgui: LibGui 5.4.2+1.18.2
				jankson: Jankson 4.0.0+j1.2.0
					blue_endless_jankson: jankson 1.2.1
				libninepatch: LibNinePatch 1.1.0
		jade: Jade 5.99.5
		jamlib: JamLib 0.0.5
		java: OpenJDK 64-Bit Server VM 17
		jumpoverfences: JumpOverFences 1.16-0.0.3
		konkrete: Konkrete 1.3.3
		krypton: Krypton 0.1.9
			com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		lambdynlights: LambDynamicLights 2.1.0+1.17
			pride: Pride Lib 1.1.0+1.17
			spruceui: SpruceUI 3.3.0+1.17
				org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		lanserverproperties: Lan Server Properties 1.8
		lapisreserve: Lapis Reserve 1.0.8
		lazydfu: LazyDFU 0.1.2
		legendarytooltips: Legendary Tooltips 1.2.5
		libraryferret: Library Ferret 2.0.0
		limitmobspawn: LimitMobSpawn 18.2-fabric
		lithium: Lithium 0.7.10
		maxhealthfix: MaxHealthFix 5.0.1
		memoryleakfix: memory Leak Fix 1.18.2-0.3.5
		memorysettings: Memorysettings Mod 1.18.2-2.2
		minecraft: Minecraft 1.18.2
		minieffects: Mini Effects 4.1.0
		mining_dims: Mining Dimensions 1.3.8
			customportalapi: Custom Portal Api 0.0.1-beta50-1.18
			pugh_lib: Pugh Lib 1.3.0
		mob_catcher: Mob Catcher 1.1.27
		modmenu: Mod Menu 3.2.3
		morevillagers: More Villagers 3.3.2
		mousetweaks: Mouse Tweaks 2.22
		namepain: Name Pain 1.4.0
		naturescompass: Nature's Compass 1.18.2-2.0.3-fabric
		netherportalfix: NetherPortalFix 9.0.0
		ngv: Nether Gold Veins 1.2.0
		ninjaphenix_container_lib: NinjaPhenix's Container Library 1.3.0
		no_angled_brackets: No Angled Brackets 1.0.0
		no_fog: No Fog 1.2.2+1.16.5-1.18.2
		nodami: No Damage Immunity(NoDamI) Reload Mod 1.0.1
		notenoughcrashes: Not Enough Crashes 4.1.6+1.18.2
		pickupnotifier: Pick Up Notifier 3.2.0
			cardinal-components-base: Cardinal Components API (base) 4.1.4
			cardinal-components-entity: Cardinal Components API (entities) 4.1.4
		pling: Pling 1.5.0
		polymorph: Polymorph 0.0.21-1.18.2
			cardinal-components-block: Cardinal Components API (blocks) 4.1.4
			cardinal-components-item: Cardinal Components API (items) 4.1.4
		presencefootsteps: Presence Footsteps 1.5.1
			kirin: Kirin UI 1.10.0
		puzzleslib: Puzzles Lib 3.3.5
		quarryplus: QuarryPlus 18.4.573
		quickhomes: QuickHomes 1.18.2-1.3.0
		rare-ice: Rare Ice 0.4.1
		reborncore: Reborn Core 5.2.0
		reroll: Reroll 1.5.0-1.18.2
		rightclickharvest: Right Click Harvest 2.1.1
		roughlyenoughitems: Roughly Enough Items 8.3.502
		roughlyenoughprofessions: Roughly Enough Professions 1.0.1
		roughlyenoughresources: Roughly Enough Resources 2.5.0
		roughlysearchable: Roughly Searchable 2.4.1+1.18.2
		scannable: Scannable 1.7.7
		seamless_loading_screen: Seamless Loading Screen 1.4.0+1.18.2
		seedfix: Seed Fix 1.0.1
		simple_backpack: SimpleBackpack 1.2.37
		skylorlib: SkyLib 1.3.35
		smoothboot: Smooth Boot 1.18.2-1.7.0
		smoothchunk: Smooth chunk save Mod 1.18.2-1.9
		soaringstructures2: Soaring Structures 2 1.18.2 - 2.3.1
		sodium: Sodium 0.4.1+build.15
			org_joml_joml: joml 1.10.2
		sound_physics_remastered: Sound Physics Remastered 1.18.2-1.0.6
		spark: spark 1.9.11
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		starlight: Starlight 1.0.2+fabric.89b8d9f
		stoneholm: Stoneholm 1.4.3
		t_and_t: Towns and Towers - Structure Add-on 1.6
		techreborn: Tech Reborn 5.2.0
		terrablender: TerraBlender 1.1.0.102
			com_electronwill_night-config_core: core 3.6.4
			com_electronwill_night-config_toml: toml 3.6.4
		terrarianslimes: Terrarian Slimes 1.2.1-BETA+1.18
		the_extractinator: The Extractinator 1.0.8
		tipthescales: Tip The Scales 5.0.6
		torohealth: ToroHealth Damage Indicators 1.18-fabric-2
		totemmod: Wither Totems Mod 0.3.5-1.18.2-pre2
		totw_additions: Towers of the Wild: Additions 1.2.1
		trinkets: Trinkets 3.3.1
		universal_ores: Universal Ores 1.3.0
		vanillatweaks: VanillaTweaks 1.5.58
		visuality: Visuality 0.4.2
			goosik-config: goosik-config 0.2.0
			tlcosmetica: Cosmetica 0.4.0
		waystones: Waystones 2.5.5+mc1.18.2
		wolveswitharmor: Wolves With Armor 1.7.1-1.18.2
			maybe-data: Maybe data 1.2.1-1.18.2
			static-content: Static Content 1.0.1-1.16.2
				staticdata: Static Data 1.1.2
		woodarmor: Wooden Armors (+ Stone Armor) fabric-1.18.2-v1.0.1
		woodarmorhorse: Wooden Horse Armors fabric-1.18.2-v1.0.1
		woodenhoppers: Wooden Hoppers 1.2.0
		worldedit: WorldEdit 7.2.10+1742f98
		xaerominimap: Xaero's Minimap 22.10.0
		xaeroworldmap: Xaero's World Map 1.24.0
		xp_storage: XP Storage 1.4.3+1.18
		yigd: You're in Grave Danger 1.3.7
		yosbr: YOSBR 0.1.1
		yungsapi: YUNG's API 1.18.2-Fabric-2.0.8
		yungsbridges: YUNG's Bridges 1.18.2-Fabric-2.1.0
		yungsextras: YUNG's Extras 1.18.2-Fabric-2.1.0
	Loaded Shaderpack: (off)
	Flywheel Backend: GL33 Instanced Arrays
	Server Running: true
	Player Count: 1 / 8; [class_3222['valkyrienyanko'/243, l='ServerLevel[New World]', x=44.50, y=63.00, z=32.50]]
	Data Packs: vanilla, createplus/createplus-core, Fabric Mods
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Client Crashes Since Restart: 0
	Integrated Server Crashes Since Restart: 1
	Suspected Mods: Minecraft (minecraft), Hardcore Torches (hardcore_torches), Roughly Enough Resources (roughlyenoughresources)
```

**Comment by valkyrienyanko** [comment]
Looks like this is throwing the `ExceptionInInitializerError` for some reason.

https://github.com/WolfieWaffle/Hardcore-Torches-Fabric/blob/f4fd5d5f494e58a857312ea6321310d7c4bdcabc/src/main/java/com/github/wolfiewaffle/hardcore_torches/loot/FatLootNumberProvider.java#L33-L36

**Comment by Jurklein** [comment]
I am getting the same error. Playing this mod with the "Better Minecraft - Fabric" v19.1 modpack.

java.lang.ExceptionInInitializerError
	at com.github.wolfiewaffle.hardcore_torches.loot.FatLootNumberProvider.method_365(FatLootNumberProvider.java:35)
	at net.minecraft.class_5330$class_5333.serialize(class_5330.java:114)
	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81)
	at com.google.gson.Gson.toJson(Gson.java:735)
	at com.google.gson.Gson.toJsonTree(Gson.java:628)
	at com.google.gson.Gson.toJsonTree(Gson.java:607)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.serialize(TreeTypeAdapter.java:155)
	at net.minecraft.class_55$class_57.method_357(class_55.java:184)
	at net.minecraft.class_55$class_57.serialize(class_55.java:169)
	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
	at com.google.gson.internal.bind.ArrayTypeAdapter.write(ArrayTypeAdapter.java:95)
	at com.google.gson.Gson.toJson(Gson.java:735)
	at com.google.gson.Gson.toJsonTree(Gson.java:628)
	at com.google.gson.Gson.toJsonTree(Gson.java:607)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.serialize(TreeTypeAdapter.java:155)
	at net.minecraft.class_52$class_54.method_339(class_52.java:240)
	at net.minecraft.class_52$class_54.serialize(class_52.java:210)
	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81)
	at com.google.gson.Gson.toJson(Gson.java:735)
	at com.google.gson.Gson.toJsonTree(Gson.java:628)
	at com.google.gson.Gson.toJsonTree(Gson.java:607)
	at uk.me.desert_island.rer.RoughlyEnoughResources.sendLootToPlayers(RoughlyEnoughResources.java:53)
	at net.minecraft.class_3324.handler$hih002$onPlayerConnect(class_3324.java:11485)
	at net.minecraft.class_3324.method_14570(class_3324.java:286)
	at net.minecraft.class_3248.method_33800(class_3248.java:140)
	at net.minecraft.class_3248.method_14384(class_3248.java:127)
	at net.minecraft.class_3248.redirect$dpb000$handlePlayerJoin(class_3248.java:563)
	at net.minecraft.class_3248.method_18785(class_3248.java:77)
	at net.minecraft.class_2535.method_10754(class_2535.java:242)
	at net.minecraft.class_3242.method_14357(class_3242.java:182)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Registry is already frozen (trying to add key ResourceKey[minecraft:loot_number_provider_type / hardcore_torches:fat])
	at net.minecraft.class_2370.method_40274(class_2370.java:81)
	at net.minecraft.class_2370.method_31051(class_2370.java:91)
	at net.minecraft.class_2370.method_10273(class_2370.java:87)
	at net.minecraft.class_2370.method_10272(class_2370.java:135)
	at net.minecraft.class_2378.method_39197(class_2378.java:508)
	at net.minecraft.class_2378.method_10230(class_2378.java:504)
	at com.github.wolfiewaffle.hardcore_torches.loot.HCTLootNumberProviderTypes.register(HCTLootNumberProviderTypes.java:13)
	at com.github.wolfiewaffle.hardcore_torches.loot.HCTLootNumberProviderTypes.<clinit>(HCTLootNumberProviderTypes.java:10)
	... 37 more

**Comment by WolfieWaffle** [comment]
hm, do you know if the JSONs have been edited at all in those packs? the crash reports seem to mention JSON or GSON, I will try to download the pack and see

**Comment by WolfieWaffle** [comment]
so, apparently, I fix this by adding a blank method and calling it, because of classloading stuff. I'll upload the file here in case it takes a while on curseforge.

[HCT #7 Fix.zip](https://github.com/WolfieWaffle/Hardcore-Torches-Fabric/files/9128893/HCT.7.Fix.zip)

**Comment by valkyrienyanko** [comment]
thank you! ❤️
