### ISSUE TITLE
Crash open new world

### ISSUE THREAD

**Issue by lostopkk** [WolfieWaffle/Hardcore-Torches-Fabric#8]
java.lang.IllegalArgumentException: Cannot get property class_2746{name=on_wall, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{hardcore_torches:lit_lantern}
	at net.minecraft.class_2688.method_11654(class_2688.java:98)
	at net.minecraft.class_3749.handler$ign001$getOutlineShape(class_3749.java:619)
	at net.minecraft.class_3749.method_9530(class_3749.java:56)
	at com.github.wolfiewaffle.hardcore_torches.block.AbstractLanternBlock.method_9530(AbstractLanternBlock.java:233)
	at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:855)
	at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:851)
	at net.minecraft.class_2248.method_9579(class_2248.java:313)
	at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1103)
	at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:708)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.class_2246.method_26979(class_2246.java:1078)
	at net.minecraft.class_5350.method_40421(class_5350.java:92)
	at net.minecraft.class_7237.method_42097(class_7237.java:35)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_4014.method_18365(class_4014.java:69)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_4014.method_18367(class_4014.java:68)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at net.minecraft.class_4014$1.method_18374(class_4014.java:51)
	at net.minecraft.class_1255.redirect$bic000$redirectExecuteTask(class_1255.java:521)
	at net.minecraft.class_1255.method_16075(class_1255.java:131)
	at net.minecraft.class_1255.method_18857(class_1255.java:140)
	at net.minecraft.class_525.method_31130(class_525.java:158)
	at net.minecraft.class_528.method_43462(class_528.java:137)
	at net.minecraft.class_528.method_43458(class_528.java:101)
	at net.minecraft.class_528.<init>(class_528.java:96)
	at net.minecraft.class_526.method_25426(class_526.java:66)
	at net.minecraft.class_437.method_41843(class_437.java:391)
	at net.minecraft.class_437.method_25423(class_437.java:382)
	at net.minecraft.class_310.method_1507(class_310.java:1001)
	at net.minecraft.class_442.method_19861(class_442.java:158)
	at net.minecraft.class_4185.method_25306(class_4185.java:40)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:120)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_442.method_25402(class_442.java:324)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:204)
	at net.minecraft.class_1041.method_15998(class_1041.java:310)
	at net.minecraft.class_310.method_1523(class_310.java:1171)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)

**Comment by WolfieWaffle** [comment]
how did you get this crash? are you using any other mods?

**Comment by drgnmstrc** [comment]
Hi there, I managed to replicate this crash! The culprit for me was "[Lanterns Belong on Walls](https://www.curseforge.com/minecraft/mc-mods/lanterns-bow)", whose lantern changes I imagine create issues with the refilling system. Removing it fixes the world generation crash.

**Comment by WolfieWaffle** [comment]
hm, I wonder if it would be possible to add compatibility for it

**Comment by drgnmstrc** [comment]
I haven't built a mod or worked java extensively but I imagine if you can find a way of plugging your lanterns into the extra class it seems to be creating (the on_wall property it adds for lanterns) that would fix it. I know it's certainly possible to have that sort of dynamic compatibility - perhaps hacking apart a compat mod would help for direction if needed, though doing something like dynamically adding wood variants seems easier than nesting a modded lantern within another mod's property. Might be really easy to do a simple check to add the hardcore lantern properties to the wall facing lanterns, but yeah I'm no expert. Best of luck if you decide to take the endeavor!

**Comment by SylisMC** [comment]
New [issue](https://github.com/WolfieWaffle/Hardcore-Torches-Fabric/issues/11) Opened on this with more details, also created a thread on [Lanterns Belong on Walls](https://github.com/ThePoultryMan/Lanterns-Belong-On-Walls/issues/13) 
They may not be related but its the same two mods
